POST http://localhost:9090/account/register
Content-Type: application/json

{
  "id": "jinwoo",
  "password": "1234",
  "name": "이진우",
  "email": "jinwoo7654@naver.com"
}

###
POST http://localhost:9090/account/login
Content-Type: application/json

{
  "id": "jinwoo",
  "password": "1234"
}

###
GET http://localhost:9090/account/info/jinwoo

###
DELETE http://localhost:9090/account/delete
Content-Type: application/json

{
  "id": "jinwoo",
  "password": "1234"
}